name: "Tests"
on: [push, pull_request]

jobs:
  # flake8:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: Set up Python 3.7
  #       uses: actions/setup-python@v1
  #       with:
  #         python-version: 3.7
  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install flake8
  #     - name: Lint with flake8
  #       run: |
  #         flake8 src

  test-sphinx-versions:
    runs-on: ubuntu-latest
    env:
      SPHINX: ${{ matrix.SPHINX }}
      BIBTEX: ${{ matrix.BIBTEX }}
    strategy:
      matrix:
        SPHINX: ["==1.8.0", "==1.8.5", "==2.0.0", "==2.1.0", "==2.2.0"]
        include:
          - SPHINX: "==1.8.0"
            BIBTEX: "==0.4.2"
          - SPHINX: "==1.8.5"
            BIBTEX: "==0.4.2"

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Setup conda
        uses: s-weigand/setup-conda@master
        with:
          activate-conda: false
          conda-channels: conda-forge
      - name: Install dependencies
        run: |
          conda install -y pandoc librsvg tectonic
          python -m pip install Sphinx$SPHINX
          python -m pip install .
          python -m pip install $(grep -iv bibtex doc/requirements.txt)
          python -m pip install sphinxcontrib-bibtex$BIBTEX
      - name: Show installed dependencies
        if: always()
        run: |
          python --version
          python -c "import nbsphinx; print('nbsphinx.__version__==', nbsphinx.__version__)"
          pandoc -v
          pip freeze
      - name: Build docs HTML
        run: python -m sphinx doc/ doc/_build/html/ -W -b html
      - name: Build docs LaTeX
        run: python -m sphinx doc/ doc/_build/latex/ -W -b latex
      - name: Build docs ePub
        run: python -m sphinx doc/ doc/_build/epub/ -W -b epub
      - name: Cache Tectonic Packages
        uses: actions/cache@v1
        with:
          path: ~/.cache/Tectonic
          key: ${{ runner.os }}-tectonic-packages
      - name: Build PDF from LaTeX
        run: tectonic doc/_build/latex/nbsphinx.tex
      - name: Upload _build folder
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: docs-sphinx${{ matrix.SPHINX }}
          path: doc/_build

  test-python3:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup conda
        uses: s-weigand/setup-conda@master
        with:
          activate-conda: false
          conda-channels: conda-forge
      - name: Install dependencies
        run: |
          conda install -y pandoc librsvg tectonic
          python -m pip install Sphinx
          python -m pip install .
          python -m pip install -r doc/requirements.txt
      - name: Show installed dependencies
        if: always()
        run: |
          python --version
          python -c "import nbsphinx; print('nbsphinx.__version__==', nbsphinx.__version__)"
          pandoc -v
          pip freeze
      - name: Build docs HTML
        run: python -m sphinx doc/ doc/_build/html/ -W -b html
      - name: Build docs LaTeX
        run: python -m sphinx doc/ doc/_build/latex/ -W -b latex
      - name: Build docs ePub
        run: python -m sphinx doc/ doc/_build/epub/ -W -b epub
      - name: Cache Tectonic Packages Linux
        if: runner.os == 'Linux'
        uses: actions/cache@v1
        with:
          path: ~/.cache/Tectonic
          key: ${{ runner.os }}-tectonic-packages
      - name: Cache Tectonic Packages MacOs
        if: runner.os == 'macOS'
        uses: actions/cache@v1
        with:
          path: ~/Library/Caches/Tectonic
          key: ${{ runner.os }}-tectonic-packages
      - name: Build PDF from LaTeX
        run: tectonic doc/_build/latex/nbsphinx.tex
      - name: Upload _build folder
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: docs-${{ matrix.os }}-py${{ matrix.python-version }}
          path: doc/_build

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    needs: [test-sphinx-versions, test-python3]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U .
      - name: Build dist
        run: |
          python setup.py sdist bdist_wheel
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
